# Site settings
title: Kaiser • Granade
email: wedding@kaiser-granade.com
# TODO: uncomment this once DNS has settled down.
# url: http://wedding.kaiser-granade.com
url: http://www.cgranade.com/wedding/
baseurl: http://www.cgranade.com/wedding
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Sarah Kaiser and Chris Granade

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/cgranade
  - title: twitter
    url: https://twitter.com/crazy4pi314
  - title: github
    url: https://github.com/cgranade/wedding

# Build settings
markdown: kramdown
permalink: pretty
